// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/interceptor/servicetest/servicetest.proto

package servicetest

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCallRequest) Reset() {
	*x = TestCallRequest{}
	mi := &file_internal_interceptor_servicetest_servicetest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCallRequest) ProtoMessage() {}

func (x *TestCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interceptor_servicetest_servicetest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCallRequest.ProtoReflect.Descriptor instead.
func (*TestCallRequest) Descriptor() ([]byte, []int) {
	return file_internal_interceptor_servicetest_servicetest_proto_rawDescGZIP(), []int{0}
}

func (x *TestCallRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestCallResponse) Reset() {
	*x = TestCallResponse{}
	mi := &file_internal_interceptor_servicetest_servicetest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCallResponse) ProtoMessage() {}

func (x *TestCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interceptor_servicetest_servicetest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCallResponse.ProtoReflect.Descriptor instead.
func (*TestCallResponse) Descriptor() ([]byte, []int) {
	return file_internal_interceptor_servicetest_servicetest_proto_rawDescGZIP(), []int{1}
}

func (x *TestCallResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_interceptor_servicetest_servicetest_proto protoreflect.FileDescriptor

const file_internal_interceptor_servicetest_servicetest_proto_rawDesc = "" +
	"\n" +
	"2internal/interceptor/servicetest/servicetest.proto\"!\n" +
	"\x0fTestCallRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10TestCallResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2{\n" +
	"\vTestService\x121\n" +
	"\bTestCall\x12\x10.TestCallRequest\x1a\x11.TestCallResponse\"\x00\x129\n" +
	"\x0eTestCallStream\x12\x10.TestCallRequest\x1a\x11.TestCallResponse\"\x000\x01B>Z<github.com/openkcm/registry/internal/interceptor/servicetestb\x06proto3"

var (
	file_internal_interceptor_servicetest_servicetest_proto_rawDescOnce sync.Once
	file_internal_interceptor_servicetest_servicetest_proto_rawDescData []byte
)

func file_internal_interceptor_servicetest_servicetest_proto_rawDescGZIP() []byte {
	file_internal_interceptor_servicetest_servicetest_proto_rawDescOnce.Do(func() {
		file_internal_interceptor_servicetest_servicetest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_interceptor_servicetest_servicetest_proto_rawDesc), len(file_internal_interceptor_servicetest_servicetest_proto_rawDesc)))
	})
	return file_internal_interceptor_servicetest_servicetest_proto_rawDescData
}

var file_internal_interceptor_servicetest_servicetest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_interceptor_servicetest_servicetest_proto_goTypes = []any{
	(*TestCallRequest)(nil),  // 0: TestCallRequest
	(*TestCallResponse)(nil), // 1: TestCallResponse
}
var file_internal_interceptor_servicetest_servicetest_proto_depIdxs = []int32{
	0, // 0: TestService.TestCall:input_type -> TestCallRequest
	0, // 1: TestService.TestCallStream:input_type -> TestCallRequest
	1, // 2: TestService.TestCall:output_type -> TestCallResponse
	1, // 3: TestService.TestCallStream:output_type -> TestCallResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_interceptor_servicetest_servicetest_proto_init() }
func file_internal_interceptor_servicetest_servicetest_proto_init() {
	if File_internal_interceptor_servicetest_servicetest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_interceptor_servicetest_servicetest_proto_rawDesc), len(file_internal_interceptor_servicetest_servicetest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interceptor_servicetest_servicetest_proto_goTypes,
		DependencyIndexes: file_internal_interceptor_servicetest_servicetest_proto_depIdxs,
		MessageInfos:      file_internal_interceptor_servicetest_servicetest_proto_msgTypes,
	}.Build()
	File_internal_interceptor_servicetest_servicetest_proto = out.File
	file_internal_interceptor_servicetest_servicetest_proto_goTypes = nil
	file_internal_interceptor_servicetest_servicetest_proto_depIdxs = nil
}
