version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomodguard
    - ireturn
    - lll
    - mnd
    - musttag
    - nlreturn
    - noctx
    - noctx
    - noinlineerr
    - protogetter
    - revive
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: camel
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true
    testifylint:
      disable:
        - require-error
  exclusions:
    rules:
      - path: "_test.go"
        linters:
          - funlen
          - maintidx
          - goconst
          - dupl
      - path: "service/error.go"
        linters:
          - ireturn
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/openkcm/registry)
        - blank
        - dot
        - alias
        - localmodule
