{
 "title": "Registry Metrics",
 "time": { "from": "2024-11-29T06:11:57.193Z", "to": "2024-11-29T10:38:43.181Z" },
 "panels": [
  {
   "title": "GRPc Requests total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) ({\"grpc_request_count_total\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Current heap memory allocation",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes/1024/1024"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "GRPc Methods Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GRPC Methods Time 1 Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (operation, le) (rate({\"grpc.request_duration_milliseconds_bucket\"}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "GRPC Methods Time 0.95 Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (operation, le) (rate({\"grpc.request_duration_milliseconds_bucket\"}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "GRPC Methods Time 0.99 Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (operation, le) (rate({\"grpc.request_duration_milliseconds_bucket\"}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "GRPC Methods Time 0.5 Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (operation, le) (rate({\"grpc.request_duration_milliseconds_bucket\"}[5m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "System Registrations by Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"systems.registered_total\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "System Deletion by Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"systems.deleted_total\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Tenant Registrations by Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"tenants.registered_total\"}",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Tenant Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) ({\"tenants.count\"})",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}