name: Helm

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'

permissions:
  packages: write

env:
  OCI_URL: ghcr.io/openkcm

jobs:
  release:
    uses: openkcm/build/.github/workflows/chart-release.svc.yaml@7410b3341d4752b66e1b68327f8a9d8ae3ed81c0 # main
