name: Helm Test

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths-ignore:
      - 'charts/**'
      - 'docs/**'
      - 'LICENSES/**'
      - '.releases/**'
      - '.github/**'
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Init
        id: init
        env:
          EVENT_NAME: ${{ github.event_name }}
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          REPOSITORY: ${{ github.repository }}
        run: |
          if [[ "$EVENT_NAME" == "pull_request" ]]; then
          echo "internal_pr=$([[ "$HEAD_REPO" == "$REPOSITORY" ]] && echo true || echo false)" >> "$GITHUB_OUTPUT"
          else
          echo "internal_pr=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate token from GitHub App
        id: generate-token
        if: steps.init.outputs.internal_pr == 'true' && github.actor != 'dependabot[bot]' && secrets.APP_PUSH_TAG_ID != ''
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APP_PUSH_TAG_ID }}
          private-key: ${{ secrets.APP_PUSH_TAG_PRIVATE_KEY }}
          permission-contents: read

      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.generate-token.outputs.token || github.token }}
          fetch-tags: true
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Build binary and Docker image
        run: make docker-build

      - name: Setup k3s
        run: |
          go install github.com/k3d-io/k3d/v5@v5.8.3
          k3d --version
          k3d cluster create k3scluster --wait --image=rancher/k3s:latest
          while ! kubectl get serviceaccount default >/dev/null; do sleep 2; done
      - name: Import the Docker image
        run: k3d image import registry:dev -c k3scluster

      - name: Install Dependencies
        run: make helm-install-dependencies

      - name: Install Registry
        run: make helm-install-registry

      - name: Run Helm tests
        run: make helm-test