name: Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  do:
    uses: openkcm/build/.github/workflows/labeler.yaml@a3b997812361a5824f246b6fc600284aafb05d5a # main
    secrets: inherit # zizmor: ignore[secrets-inherit]
