name: New Release (Manual Trigger)

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    uses: openkcm/build/.github/workflows/release.manual.yaml@7410b3341d4752b66e1b68327f8a9d8ae3ed81c0 # main
    secrets: inherit # zizmor: ignore[secrets-inherit]

