name: Sonar Analysis Secure

on: # zizmor: ignore[dangerous-triggers]
  workflow_run:
    workflows: ["Quality"]
    types:
      - completed

permissions:
  contents: read
  statuses: write

jobs:
  check:
    uses: openkcm/build/.github/workflows/sonar.yaml@7410b3341d4752b66e1b68327f8a9d8ae3ed81c0 # main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
